#!/bin/sh
############################################################
# Shell script to pull information from the header of a    #
# NetCDF output file generated by ADCIRC through the ASGS  #
# and copy it to a text file which will be read by a       #
# ParaView Python script to create an annotation.          #
#                                                          #
# Should be used with ASGS results that are associated     #
# with an NHC advisory or a NAM run, since the specific    #
# header information extracted is customized for these     #
# use cases.                                               #
#                                                          #
# Input : The name of the netCDF file; ex: fort.63.nc      #
#                                                          #
# Output: A text file; if it does not exist, it is created #
# and if it exists it is overwritten.                      #
#                                                          #
# Requirements: You must have the ncdump utility on your   #
# path (requires a NetCDF installation).                   #
############################################################

ncdump -h "$1" | grep ":model" > label_info.txt
{
    ncdump -h "$1" | grep ":agrid"
    ncdump -h "$1" | grep ":title"
    ncdump -h "$1" | grep ":rundes"
    ncdump -h "$1" | grep ":runid" 
    ncdump -h "$1" | grep "time:units"
} >> label_info.txt
